# Generated by Django 4.2 on 2024-06-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_article_tag_image_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Отправлен', 'shipped'), ('Доставлен', 'delivered')], default='Отправлен', max_length=50),
        ),
    ]
