# Generated by Django 4.2 on 2024-06-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='salary',
            field=models.FloatField(),
        ),
    ]
