# Generated by Django 4.2 on 2024-06-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_doctor_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabledays',
            name='date',
            field=models.DateField(),
        ),
    ]
