# Generated by Django 4.2 on 2024-06-13 22:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_hospitalcategory_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
